'use client'

import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { useMemo, useState } from 'react'
import type { Listing, Price, PriceAnalytics, Product, Signal, Strategy } from '@/lib/types'

type Props = { product:Product; listings:Listing[]; prices:Price[]; analytics:PriceAnalytics; signals:Signal[]; strategy?:Strategy|null }
type WindowKey = 7|30|90|180|0
type TabKey = 'overview'|'platforms'|'evidence'|'history'

const bestPrice=(p?:Price|null)=>{if(!p)return null;const v=p.checkout_price??p.promotion_price??p.list_price;return typeof v==='number'?v+(p.shipping_fee??0):null}
const money=(v?:number|null,f='—',currency='CNY')=>{
  if(typeof v!=='number'||Number.isNaN(v))return f
  const normalized=currency.toUpperCase()
  try{return new Intl.NumberFormat(normalized==='CNY'?'zh-CN':'en-US',{style:'currency',currency:normalized,maximumFractionDigits:0}).format(v)}catch{return `${normalized} ${Math.round(v).toLocaleString('en-US')}`}
}
const shortDate=(v?:string|null)=>v?new Date(v).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}):'—'
const dateTime=(v?:string|null)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'
const statusLabel=(s?:string|null)=>({VERIFIED_CHECKOUT:'已核验到手价',VISIBLE_PRICE:'仅网页可见价',UNVERIFIED:'未核验证据',INVALID:'无效记录'}[s??'']??s??'未知状态')
const tone=(s?:string|null)=>s==='VERIFIED_CHECKOUT'?'verified':s==='VISIBLE_PRICE'?'visible':s==='INVALID'?'invalid':'unverified'
const within=(v:string,d:WindowKey)=>d===0||Date.now()-new Date(v).getTime()<=d*86400000

function TrendChart({prices,strategy,days}:{prices:Price[];strategy?:Strategy|null;days:WindowKey}){
  const currencyCounts=prices.reduce<Record<string,number>>((counts,p)=>{if(bestPrice(p)!=null){const currency=(p.currency||'CNY').toUpperCase();counts[currency]=(counts[currency]??0)+1}return counts},{})
  const currency=(strategy?.currency||Object.entries(currencyCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'CNY').toUpperCase()
  const points=useMemo(()=>prices.filter(p=>(p.currency||'CNY').toUpperCase()===currency&&within(p.captured_at,days)).map(p=>({...p,n:bestPrice(p)})).filter((p):p is Price&{n:number}=>typeof p.n==='number').sort((a,b)=>+new Date(a.captured_at)-+new Date(b.captured_at)),[prices,days,currency])
  if(points.length<2)return <div className="chart-empty">当前时间范围内数据不足，至少需要 2 条有效价格记录。</div>
  const W=920,H=320,L=55,R=22,T=20,B=38,refs=[strategy?.trigger_price,strategy?.strong_buy_price].filter((v):v is number=>typeof v==='number'),vals=points.map(p=>p.n),min=Math.min(...vals,...refs),max=Math.max(...vals,...refs),spread=Math.max(1,max-min),lo=min-spread*.12,hi=max+spread*.12
  const x=(i:number)=>L+i/Math.max(1,points.length-1)*(W-L-R),y=(v:number)=>T+(1-(v-lo)/(hi-lo))*(H-T-B),path=points.map((p,i)=>`${i?'L':'M'} ${x(i)} ${y(p.n)}`).join(' ')
  return <div className="real-chart"><svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" role="img" aria-label="真实价格趋势图"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="white" stopOpacity=".2"/><stop offset="1" stopColor="white" stopOpacity="0"/></linearGradient></defs>
    {[0,1,2,3,4].map(i=>{const v=lo+(hi-lo)*i/4;return <g key={i}><line x1={L} x2={W-R} y1={y(v)} y2={y(v)} stroke="#282828" strokeDasharray="4 7"/><text x={L-8} y={y(v)+4} textAnchor="end" fill="#666" fontSize="11">{money(v,'—',currency)}</text></g>})}
    {strategy?.trigger_price!=null&&<><line x1={L} x2={W-R} y1={y(strategy.trigger_price)} y2={y(strategy.trigger_price)} stroke="#888" strokeDasharray="7 6"/><text x={W-R} y={y(strategy.trigger_price)-6} textAnchor="end" fill="#aaa" fontSize="11">目标价</text></>}
    {strategy?.strong_buy_price!=null&&<><line x1={L} x2={W-R} y1={y(strategy.strong_buy_price)} y2={y(strategy.strong_buy_price)} stroke="#fff" strokeDasharray="2 7"/><text x={W-R} y={y(strategy.strong_buy_price)-6} textAnchor="end" fill="#ddd" fontSize="11">强力入手线</text></>}
    <path d={`${path} L ${x(points.length-1)} ${H-B} L ${x(0)} ${H-B} Z`} fill="url(#area)"/><path d={path} fill="none" stroke="#f3f3ef" strokeWidth="2.4" vectorEffect="non-scaling-stroke"/>
    {points.map((p,i)=><circle key={p.id} cx={x(i)} cy={y(p.n)} r={p.verification_status==='VERIFIED_CHECKOUT'?4.5:3} fill={p.verification_status==='VERIFIED_CHECKOUT'?'#fff':'#555'} stroke="#050505" strokeWidth="1.5"/>)}
    <text x={L} y={H-10} fill="#666" fontSize="11">{shortDate(points[0].captured_at)}</text><text x={W-R} y={H-10} textAnchor="end" fill="#666" fontSize="11">{shortDate(points.at(-1)?.captured_at)}</text></svg><div className="chart-legend"><span><i className="verified-dot"/>已核验价</span><span><i/>证据价</span><span>{currency} · {points.length} 条记录</span></div></div>
}

export function ProductIntelligence({product,listings,prices,analytics,signals,strategy}:Props){
  const reduced=useReducedMotion(),[days,setDays]=useState<WindowKey>(30),[tab,setTab]=useState<TabKey>('overview'),[open,setOpen]=useState<number|null>(null)
  const verified=prices.filter(p=>p.verification_status==='VERIFIED_CHECKOUT'),latestVerifiedRecord=verified[0]??null,latestVerified=bestPrice(latestVerifiedRecord),distance=latestVerified!=null&&strategy?.trigger_price!=null?latestVerified-strategy.trigger_price:null
  const currency=(latestVerifiedRecord?.currency||strategy?.currency||analytics.currency||'CNY').toUpperCase()
  const platformRows=useMemo(()=>{const m=new Map<string,Price[]>();for(const p of prices){const k=p.platform||'未知平台';m.set(k,[...(m.get(k)||[]),p])}return [...m].map(([platform,rows])=>{const values=rows.map(item=>({item,value:bestPrice(item)})).filter((r):r is {item:Price,value:number}=>typeof r.value==='number'),v=values.filter(r=>r.item.verification_status==='VERIFIED_CHECKOUT').sort((a,b)=>a.value-b.value),best=v[0]??values.sort((a,b)=>a.value-b.value)[0],newest=rows.slice().sort((a,b)=>+new Date(b.captured_at)-+new Date(a.captured_at))[0];return{platform,best,newest,count:rows.length,verified:v.length}}).sort((a,b)=>(a.best?.value??Infinity)-(b.best?.value??Infinity))},[prices])
  const judgment=latestVerified==null?['先核验，再决策','当前没有可执行的已核验到手价。网页可见价和未核验价格只能作为线索。']:strategy?.strong_buy_price!=null&&latestVerified<=strategy.strong_buy_price?['进入强力入手区',`当前已核验价 ${money(latestVerified,'—',currency)}，低于强力入手线 ${money(strategy.strong_buy_price,'—',currency)}。`]:strategy?.trigger_price!=null&&latestVerified<=strategy.trigger_price?['已触发购买策略',`当前已核验价低于目标价 ${money(strategy.trigger_price,'—',currency)}。`]:analytics.latest_percentile!=null&&analytics.latest_percentile<=30?['价格位置偏低',`当前价格位于历史样本约第 ${Math.round(analytics.latest_percentile)} 百分位，值得继续观察。`]:['继续观察',strategy?.trigger_price!=null?`当前可信价仍高于目标价 ${money(strategy.trigger_price,'—',currency)}。`:'当前尚未设置明确目标价。']
  const metrics=[['当前可信价',money(latestVerified,'—',currency)],['30 天最低价',money(analytics.min_price,'—',currency)],['30 天中位数',money(analytics.median_price,'—',currency)],['30 天均价',money(analytics.mean_price,'—',currency)],['历史百分位',analytics.latest_percentile!=null?`${Math.round(analytics.latest_percentile)}%`:'—'],['波动率',analytics.volatility_pct!=null?`${analytics.volatility_pct.toFixed(1)}%`:'—'],['30 天变化',analytics.change_pct!=null?`${analytics.change_pct>0?'+':''}${analytics.change_pct.toFixed(1)}%`:'—'],['异常分数',analytics.anomaly_score!=null?analytics.anomaly_score.toFixed(2):'—']]
  return <div className="product-intelligence"><section className="product-hero"><div className="product-identity"><span className="product-kicker">PRODUCT INTELLIGENCE</span><h1>{product.name}</h1><p>{[product.brand,product.category,product.mount_type,product.sensor_format].filter(Boolean).join(' · ')||'摄影器材'}</p><div className="hero-badges"><span className={`evidence-badge ${tone(latestVerifiedRecord?.verification_status)}`}>{statusLabel(latestVerifiedRecord?.verification_status)}</span><span className="plain-badge">{product.is_active?'追踪中':'已暂停'}</span><span className="plain-badge">{listings.length} 个来源链接</span></div></div><div className="hero-price"><span>当前已核验到手价</span><strong>{money(latestVerified,'—',currency)}</strong><small>{latestVerifiedRecord?`核验于 ${dateTime(latestVerifiedRecord.verified_at??latestVerifiedRecord.captured_at)}`:'尚无可执行价格'}</small></div></section>
    <section className="decision-panel"><div><span>当前判断</span><h2>{judgment[0]}</h2><p>{judgment[1]}</p></div><div className="decision-distance"><span>距离目标价</span><strong>{distance==null?'—':distance<=0?`低 ${money(Math.abs(distance),'—',currency)}`:`高 ${money(distance,'—',currency)}`}</strong><small>目标价 {money(strategy?.trigger_price,'未设置',currency)}</small></div></section>
    <div className="intelligence-metrics">{metrics.map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>
    <section className="intelligence-section"><div className="section-heading"><div><span>PRICE HISTORY</span><h2>真实价格趋势</h2></div><div className="range-tabs">{([7,30,90,180,0] as WindowKey[]).map(d=><button key={d} className={days===d?'active':''} onClick={()=>setDays(d)}>{d===0?'全部':`${d}天`}</button>)}</div></div><TrendChart prices={prices} strategy={strategy} days={days}/></section>
    <section className="intelligence-section"><div className="section-heading"><div><span>DETAIL LAYERS</span><h2>深入查看</h2></div></div><div className="detail-tabs">{([['overview','核心数据'],['platforms','平台对比'],['evidence','证据链'],['history','历史记录']] as [TabKey,string][]).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div><AnimatePresence mode="wait"><motion.div key={tab} initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-6}} className="tab-panel">
      {tab==='overview'&&<div className="comparison-table"><div className="comparison-head"><span>指标</span><span>当前值</span><span>参考</span><span>判断</span></div><div><span>当前可信价</span><b>{money(latestVerified,'—',currency)}</b><span>中位数 {money(analytics.median_price,'—',currency)}</span><em>{latestVerified!=null&&analytics.median_price!=null?(latestVerified<=analytics.median_price?'低于中位数':'高于中位数'):'数据不足'}</em></div><div><span>30 天最低价</span><b>{money(analytics.min_price,'—',currency)}</b><span>相差 {latestVerified!=null&&analytics.min_price!=null?money(latestVerified-analytics.min_price,'—',currency):'—'}</span><em>{latestVerified!=null&&analytics.min_price!=null&&latestVerified<=analytics.min_price*1.05?'接近低点':'仍有空间'}</em></div><div><span>价格波动</span><b>{analytics.volatility_pct!=null?`${analytics.volatility_pct.toFixed(1)}%`:'—'}</b><span>{analytics.sample_count} 个样本</span><em>{analytics.volatility_pct!=null&&analytics.volatility_pct<=5?'较稳定':'波动明显'}</em></div><div><span>趋势</span><b>{analytics.trend||'—'}</b><span>{analytics.window_days} 天窗口</span><em>{analytics.is_sufficient?'样本充足':'样本不足'}</em></div></div>}
      {tab==='platforms'&&<div className="platform-grid">{platformRows.map(r=><article key={r.platform} className="platform-card"><div><span>{r.platform}</span><small>{r.count} 条记录 · {r.verified} 条已核验</small></div><strong>{money(r.best?.value,'—',r.best?.item.currency||'CNY')}</strong><p>{r.best?.item.seller_name||r.best?.item.title||'未知店铺'}</p><footer><span>{statusLabel(r.best?.item.verification_status)}</span><span>更新 {shortDate(r.newest?.captured_at)}</span></footer></article>)}</div>}
      {tab==='evidence'&&<div className="evidence-chain"><div className="chain-flow">{['商品链接','页面抓取','价格解析','优惠与运费','截图保存','人工核验','策略判断'].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div>)}</div><div className="evidence-records">{prices.slice(0,8).map(p=><article key={p.id} className="evidence-record"><button onClick={()=>setOpen(open===p.id?null:p.id)}><div><span className={`evidence-badge ${tone(p.verification_status)}`}>{statusLabel(p.verification_status)}</span><b>{p.platform||'未知平台'} · {money(bestPrice(p),'—',p.currency||'CNY')}</b><small>{p.seller_name||p.title||product.name}</small></div><span>{open===p.id?'−':'+'}</span></button>{open===p.id&&<div className="evidence-detail"><dl><div><dt>原始价格</dt><dd>{p.raw_price_text||money(p.list_price,'—',p.currency||'CNY')}</dd></div><div><dt>促销价</dt><dd>{money(p.promotion_price,'—',p.currency||'CNY')}</dd></div><div><dt>到手价</dt><dd>{money(p.checkout_price,'—',p.currency||'CNY')}</dd></div><div><dt>优惠信息</dt><dd>{p.coupon_text||'无'}</dd></div><div><dt>运费</dt><dd>{money(p.shipping_fee,money(0,'—',p.currency||'CNY'),p.currency||'CNY')}</dd></div><div><dt>抓取方法</dt><dd>{p.extraction_method||'未知'}</dd></div><div><dt>可信度</dt><dd>{p.confidence_score!=null?`${Math.round(p.confidence_score*100)}%`:'—'}</dd></div><div><dt>抓取时间</dt><dd>{dateTime(p.captured_at)}</dd></div></dl><div className="evidence-actions">{p.source_url&&<a href={p.source_url} target="_blank" rel="noreferrer">打开来源页面 ↗</a>}{p.screenshot_path&&<span>已保存证据截图</span>}</div></div>}</article>)}</div></div>}
      {tab==='history'&&<div className="history-table-wrap"><table className="history-table"><thead><tr><th>时间</th><th>平台</th><th>店铺 / 标题</th><th>价格</th><th>可信状态</th><th>来源</th></tr></thead><tbody>{prices.slice(0,30).map(p=><tr key={p.id}><td>{dateTime(p.captured_at)}</td><td>{p.platform||'未知'}</td><td>{p.seller_name||p.title||product.name}</td><td>{money(bestPrice(p),'—',p.currency||'CNY')}</td><td><span className={`evidence-badge ${tone(p.verification_status)}`}>{statusLabel(p.verification_status)}</span></td><td>{p.source_url?<a href={p.source_url} target="_blank" rel="noreferrer">打开 ↗</a>:'本地记录'}</td></tr>)}</tbody></table></div>}
    </motion.div></AnimatePresence></section>
    <section className="intelligence-bottom-grid"><div><span className="section-overline">STRATEGY REASONING</span><h2>策略为什么这样判断</h2><div className="reason-list">{signals.slice(0,6).map(s=><div key={s.id}><span>{s.triggered?'已触发':'观察'}</span><div><b>{s.signal_type}</b><p>{s.message||s.reason_code||'策略信号'}</p></div></div>)}{!signals.length&&<div className="empty-state">暂无策略信号。</div>}</div></div><div><span className="section-overline">CURRENT STRATEGY</span><h2>当前策略参数</h2><div className="strategy-summary"><div><span>观察价</span><b>{money(strategy?.watch_price,'未设置',currency)}</b></div><div><span>目标价</span><b>{money(strategy?.trigger_price,'未设置',currency)}</b></div><div><span>强力入手线</span><b>{money(strategy?.strong_buy_price,'未设置',currency)}</b></div><div><span>允许价格年龄</span><b>{strategy?`${strategy.max_price_age_hours} 小时`:'—'}</b></div></div></div></section>
  </div>
}
