-- V0.14 trust modules: structured price evidence, adjustments, and signal consistency.

create table if not exists public.price_evidence (
  id bigint generated by default as identity primary key,
  price_record_id bigint not null references public.price_records(id) on delete cascade,
  evidence_type text not null,
  object_path text,
  evidence_hash text,
  source_url text,
  sku_id text,
  seller_name text,
  region text,
  captured_at timestamptz,
  verified_by text,
  note text,
  created_at timestamptz not null default now(),
  constraint ck_price_evidence_type check (evidence_type in ('CHECKOUT','CART','ORDER','LISTING','SCREENSHOT','OTHER'))
);

create table if not exists public.price_adjustments (
  id bigint generated by default as identity primary key,
  price_record_id bigint not null references public.price_records(id) on delete cascade,
  adjustment_type text not null,
  label text,
  amount numeric(12,2) not null,
  currency text not null default 'CNY',
  created_at timestamptz not null default now()
);

create index if not exists idx_price_evidence_record on public.price_evidence(price_record_id, created_at desc);
create index if not exists idx_price_adjustments_record on public.price_adjustments(price_record_id, created_at desc);

insert into public.price_evidence (
  price_record_id,
  evidence_type,
  object_path,
  evidence_hash,
  source_url,
  sku_id,
  seller_name,
  region,
  captured_at,
  verified_by,
  note
)
select
  p.id,
  'CHECKOUT',
  p.screenshot_path,
  p.screenshot_hash,
  p.source_url,
  l.sku_id,
  p.seller_name,
  p.region,
  coalesce(p.verified_at, p.captured_at),
  coalesce(p.verified_by, 'legacy-import'),
  'Backfilled by V0.14 migration from existing VERIFIED_CHECKOUT record.'
from public.price_records p
left join public.product_listings l on l.id = p.listing_id
where p.verification_status = 'VERIFIED_CHECKOUT'
  and not exists (
    select 1 from public.price_evidence e where e.price_record_id = p.id
  );

alter table public.price_evidence enable row level security;
alter table public.price_adjustments enable row level security;

drop policy if exists authenticated_read_price_evidence_rows on public.price_evidence;
create policy authenticated_read_price_evidence_rows
on public.price_evidence for select
to authenticated
using (true);

drop policy if exists authenticated_read_price_adjustments on public.price_adjustments;
create policy authenticated_read_price_adjustments
on public.price_adjustments for select
to authenticated
using (true);

create unique index if not exists uq_signals_one_current_per_strategy
on public.signals(strategy_id)
where is_current = true and strategy_id is not null;

create or replace function public.enforce_verified_signal()
returns trigger
language plpgsql
as $$
declare
  price_row public.price_records%rowtype;
  strategy_row public.strategies%rowtype;
begin
  if new.triggered is not true then
    return new;
  end if;

  if new.price_record_id is null then
    raise exception 'triggered signals must reference a price_record';
  end if;

  select * into price_row from public.price_records where id = new.price_record_id;
  if not found or price_row.verification_status <> 'VERIFIED_CHECKOUT' then
    raise exception 'triggered signals must reference VERIFIED_CHECKOUT price records';
  end if;

  if price_row.product_id <> new.product_id then
    raise exception 'triggered signal product does not match price record product';
  end if;

  if new.strategy_id is not null then
    select * into strategy_row from public.strategies where id = new.strategy_id;
    if found then
      if strategy_row.product_id <> new.product_id then
        raise exception 'triggered signal product does not match strategy product';
      end if;
      if price_row.currency is null or upper(price_row.currency) <> upper(strategy_row.currency) then
        raise exception 'triggered signal currency does not match strategy currency';
      end if;
      if price_row.valid_until is not null and price_row.valid_until < now() then
        raise exception 'triggered signal price is expired';
      end if;
    end if;
  end if;

  if not exists (
    select 1
    from public.price_evidence e
    where e.price_record_id = price_row.id
      and e.evidence_type in ('CHECKOUT','CART','ORDER')
  ) then
    raise exception 'triggered signals require checkout evidence';
  end if;

  return new;
end;
$$;
