-- V0.15 production readiness: strict evidence provenance and asynchronous jobs.

create table if not exists public.evidence_uploads (
  id bigint generated by default as identity primary key,
  object_path text not null unique,
  evidence_hash text not null,
  mime_type text not null,
  size_bytes integer not null check (size_bytes > 0),
  uploaded_by text not null,
  consumed_by_price_record_id bigint references public.price_records(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.price_evidence add column if not exists upload_id bigint references public.evidence_uploads(id);
alter table public.price_evidence add column if not exists origin text not null default 'USER_METADATA';
alter table public.price_evidence add column if not exists trusted_for_strategy boolean not null default false;

create index if not exists idx_evidence_uploads_hash on public.evidence_uploads(evidence_hash);
create index if not exists idx_evidence_uploads_consumed on public.evidence_uploads(consumed_by_price_record_id);
create index if not exists idx_price_evidence_trusted_record
on public.price_evidence(price_record_id, trusted_for_strategy)
where trusted_for_strategy = true;

-- V0.14 legacy backfills remain audit evidence but are never promoted to trusted checkout proof.
update public.price_evidence
set origin = 'LEGACY_IMPORT', trusted_for_strategy = false
where note = 'Backfilled by V0.14 migration from existing VERIFIED_CHECKOUT record.';

update public.price_records p
set verification_status = 'UNVERIFIED', needs_review = true, valid_until = null
where p.verification_status = 'VERIFIED_CHECKOUT'
  and not exists (
    select 1 from public.price_evidence e
    where e.price_record_id = p.id and e.trusted_for_strategy = true
  );

update public.signals s
set triggered = false,
    signal_type = 'UNVERIFIED',
    reason_code = 'NO_TRUSTED_EVIDENCE',
    message = 'Trusted checkout evidence is required.'
where s.triggered = true
  and not exists (
    select 1
    from public.price_evidence e
    where e.price_record_id = s.price_record_id and e.trusted_for_strategy = true
  );

create table if not exists public.background_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  status text not null default 'QUEUED',
  idempotency_key text unique,
  payload_json text,
  result_json text,
  error_message text,
  worker_id text,
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  constraint ck_background_job_status check (status in ('QUEUED','RUNNING','SUCCESS','FAILED'))
);

create index if not exists idx_background_jobs_claim
on public.background_jobs(status, created_at, id)
where status = 'QUEUED';
create index if not exists idx_background_jobs_worker on public.background_jobs(worker_id, status);

alter table public.notification_deliveries add column if not exists attempts integer not null default 0;
alter table public.notification_deliveries add column if not exists next_attempt_at timestamptz;
create index if not exists idx_notification_deliveries_retry
on public.notification_deliveries(status, next_attempt_at, id)
where status in ('PENDING','RETRY','SENDING');

alter table public.evidence_uploads enable row level security;
alter table public.background_jobs enable row level security;

create or replace function public.enforce_verified_signal()
returns trigger
language plpgsql
as $$
declare
  price_row public.price_records%rowtype;
  strategy_row public.strategies%rowtype;
begin
  if new.triggered is not true then return new; end if;
  if new.price_record_id is null then raise exception 'triggered signals must reference a price_record'; end if;

  select * into price_row from public.price_records where id = new.price_record_id;
  if not found or price_row.verification_status <> 'VERIFIED_CHECKOUT' then
    raise exception 'triggered signals must reference VERIFIED_CHECKOUT price records';
  end if;
  if price_row.product_id <> new.product_id then raise exception 'triggered signal product mismatch'; end if;
  if price_row.valid_until is null or price_row.valid_until < now() then raise exception 'triggered signal price is expired'; end if;

  if new.strategy_id is not null then
    select * into strategy_row from public.strategies where id = new.strategy_id;
    if not found or strategy_row.product_id <> new.product_id then raise exception 'triggered signal strategy mismatch'; end if;
    if price_row.currency is null or upper(price_row.currency) <> upper(strategy_row.currency) then
      raise exception 'triggered signal currency mismatch';
    end if;
  end if;

  if not exists (
    select 1 from public.price_evidence e
    where e.price_record_id = price_row.id
      and e.evidence_type in ('CHECKOUT','CART','ORDER')
      and e.origin = 'OPERATOR_UPLOAD'
      and e.trusted_for_strategy = true
      and e.upload_id is not null
  ) then
    raise exception 'triggered signals require trusted checkout evidence';
  end if;
  return new;
end;
$$;
