-- V0.12 production schema for camera-market-strategy-system.
-- Source of truth: backend/app/models.py plus V0.12 Supabase handoff requirements.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_name text not null unique,
  display_name text,
  role text not null default 'owner',
  created_at timestamptz not null default now()
);

insert into public.profiles (user_name, display_name, role)
values ('ronin', 'Ronin', 'owner')
on conflict (user_name) do nothing;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  brand text,
  category text,
  mount_type text,
  sensor_format text,
  priority integer not null default 0,
  tags text,
  notes text,
  is_active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.product_listings (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  platform text not null,
  seller_name text,
  seller_type text,
  url text not null,
  sku_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint uq_listing_product_url unique (product_id, url)
);

create table if not exists public.price_records (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  listing_id bigint references public.product_listings(id) on delete set null,
  platform text,
  seller_name text,
  title text,
  list_price numeric(12,2),
  promotion_price numeric(12,2),
  checkout_price numeric(12,2),
  coupon_text text,
  shipping_fee numeric(12,2),
  stock_status text,
  verification_status text not null default 'UNVERIFIED',
  source_url text,
  screenshot_path text,
  raw_price_text text,
  raw_price_context text,
  currency text default 'CNY',
  region text,
  confidence_score double precision,
  extraction_method text,
  needs_review boolean not null default true,
  screenshot_hash text,
  review_note text,
  verified_at timestamptz,
  valid_until timestamptz,
  verified_by text,
  captured_at timestamptz not null default now(),
  constraint ck_price_record_status check (verification_status in ('VERIFIED_CHECKOUT','VISIBLE_PRICE','UNVERIFIED','INVALID')),
  constraint ck_verified_checkout_has_price check (verification_status <> 'VERIFIED_CHECKOUT' or checkout_price is not null)
);

create table if not exists public.strategies (
  id bigint generated by default as identity primary key,
  user_name text not null default 'ronin',
  product_id bigint not null references public.products(id) on delete cascade,
  strategy_name text not null,
  trigger_price numeric(12,2),
  strong_buy_price numeric(12,2),
  watch_price numeric(12,2),
  currency text not null default 'CNY',
  mode text not null default 'value_hunter',
  max_price_age_hours integer not null default 24,
  near_target_pct double precision not null default 5.0,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  strategy_id bigint references public.strategies(id) on delete set null,
  price_record_id bigint references public.price_records(id) on delete set null,
  signal_type text not null default 'WAIT',
  reason_code text,
  message text,
  triggered boolean not null default false,
  is_current boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  title text not null,
  summary text,
  markdown_content text not null,
  chart_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.flow_runs (
  id bigint generated by default as identity primary key,
  run_type text not null default 'crawl_all',
  status text not null default 'RUNNING',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_seconds double precision,
  total_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  skipped_count integer not null default 0,
  details_json text,
  log_path text
);

create table if not exists public.crawl_runs (
  id bigint generated by default as identity primary key,
  flow_run_id bigint references public.flow_runs(id) on delete set null,
  run_type text not null default 'crawl_all',
  status text not null default 'RUNNING',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_seconds double precision,
  total_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  skipped_count integer not null default 0,
  details_json jsonb,
  log_path text
);

create table if not exists public.watchlist_command_logs (
  id bigint generated by default as identity primary key,
  command_text text not null,
  action text not null,
  product_id bigint references public.products(id) on delete set null,
  result_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.external_offers (
  id bigint generated by default as identity primary key,
  provider text not null,
  external_id text not null,
  product_id bigint references public.products(id) on delete set null,
  listing_id bigint references public.product_listings(id) on delete set null,
  title text not null,
  product_url text,
  seller_name text,
  list_price numeric(12,2),
  promotion_price numeric(12,2),
  coupon_amount numeric(12,2),
  effective_price numeric(12,2),
  commission_rate double precision,
  currency text not null default 'CNY',
  stock_status text,
  raw_payload_json text,
  captured_at timestamptz not null default now(),
  expires_at timestamptz,
  constraint uq_external_offer_snapshot unique (provider, external_id, captured_at)
);

create table if not exists public.integration_runs (
  id bigint generated by default as identity primary key,
  provider text not null,
  keyword text,
  status text not null default 'RUNNING',
  request_id text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  offer_count integer not null default 0,
  ingested_count integer not null default 0,
  error_message text,
  request_json text,
  response_summary_json text
);

create table if not exists public.strategy_backtests (
  id bigint generated by default as identity primary key,
  strategy_id bigint references public.strategies(id) on delete set null,
  product_id bigint not null references public.products(id) on delete cascade,
  window_days integer not null default 180,
  series_type text not null default 'VERIFIED_CHECKOUT',
  metrics_json text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.strategy_evaluations (
  id bigint generated by default as identity primary key,
  strategy_id bigint references public.strategies(id) on delete set null,
  product_id bigint not null references public.products(id) on delete cascade,
  price_record_id bigint references public.price_records(id) on delete set null,
  status text not null default 'WAIT',
  is_buy_signal boolean not null default false,
  score double precision not null default 0,
  reasons jsonb not null default '[]'::jsonb,
  evaluated_at timestamptz not null default now()
);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  strategy_id bigint references public.strategies(id) on delete set null,
  latest_verified_price_id bigint references public.price_records(id) on delete set null,
  latest_clue_price_id bigint references public.price_records(id) on delete set null,
  status text not null default 'WAIT',
  score double precision not null default 0,
  is_buy_signal boolean not null default false,
  reasons jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.verification_audits (
  id bigint generated by default as identity primary key,
  price_record_id bigint references public.price_records(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  from_status text,
  to_status text not null,
  checkout_price numeric(12,2),
  reviewer text not null default 'ronin',
  note text,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.source_health_history (
  id bigint generated by default as identity primary key,
  provider text not null,
  status text not null,
  mode text,
  latency_ms integer,
  checked_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  signal_id bigint references public.signals(id) on delete set null,
  type text not null,
  title text not null,
  body text,
  status text not null default 'UNREAD',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.notifications(id) on delete cascade,
  channel text not null,
  status text not null default 'PENDING',
  request_json jsonb,
  response_json jsonb,
  error_message text,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_active_priority on public.products(is_active, priority desc);
create index if not exists idx_product_listings_product_active on public.product_listings(product_id, is_active);
create index if not exists idx_price_records_product_captured on public.price_records(product_id, captured_at desc);
create index if not exists idx_price_records_status_review on public.price_records(verification_status, needs_review);
create index if not exists idx_price_records_valid_until on public.price_records(valid_until);
create index if not exists idx_strategies_product_active on public.strategies(product_id, is_active);
create index if not exists idx_signals_product_current on public.signals(product_id, is_current, created_at desc);
create index if not exists idx_flow_runs_started on public.flow_runs(started_at desc);
create index if not exists idx_integration_runs_provider_started on public.integration_runs(provider, started_at desc);
create index if not exists idx_external_offers_effective on public.external_offers(provider, effective_price, captured_at desc);
create index if not exists idx_opportunities_buy_signal on public.opportunities(is_buy_signal, score desc);
create index if not exists idx_verification_audits_price on public.verification_audits(price_record_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_daily_reports_updated_at on public.daily_reports;
create trigger trg_daily_reports_updated_at
before update on public.daily_reports
for each row execute function public.set_updated_at();

drop trigger if exists trg_opportunities_updated_at on public.opportunities;
create trigger trg_opportunities_updated_at
before update on public.opportunities
for each row execute function public.set_updated_at();

create or replace function public.audit_price_verification()
returns trigger
language plpgsql
as $$
begin
  if old.verification_status is distinct from new.verification_status
     or old.checkout_price is distinct from new.checkout_price then
    insert into public.verification_audits (
      price_record_id, product_id, from_status, to_status, checkout_price, reviewer, note, source
    )
    values (
      new.id, new.product_id, old.verification_status, new.verification_status,
      new.checkout_price, coalesce(new.verified_by, 'system'), new.review_note, 'price_records_trigger'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_price_verification_audit on public.price_records;
create trigger trg_price_verification_audit
after update on public.price_records
for each row execute function public.audit_price_verification();

create or replace function public.enforce_verified_signal()
returns trigger
language plpgsql
as $$
declare
  status text;
begin
  if new.triggered is true then
    if new.price_record_id is null then
      raise exception 'Triggered signals require a price_record_id';
    end if;
    select verification_status into status from public.price_records where id = new.price_record_id;
    if status is distinct from 'VERIFIED_CHECKOUT' then
      raise exception 'Triggered signals require VERIFIED_CHECKOUT price records';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_enforce_verified_signal on public.signals;
create trigger trg_enforce_verified_signal
before insert or update on public.signals
for each row execute function public.enforce_verified_signal();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_listings enable row level security;
alter table public.price_records enable row level security;
alter table public.strategies enable row level security;
alter table public.signals enable row level security;
alter table public.daily_reports enable row level security;
alter table public.flow_runs enable row level security;
alter table public.crawl_runs enable row level security;
alter table public.watchlist_command_logs enable row level security;
alter table public.external_offers enable row level security;
alter table public.integration_runs enable row level security;
alter table public.strategy_backtests enable row level security;
alter table public.strategy_evaluations enable row level security;
alter table public.opportunities enable row level security;
alter table public.verification_audits enable row level security;
alter table public.product_events enable row level security;
alter table public.source_health_history enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_deliveries enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles','products','product_listings','price_records','strategies','signals',
    'daily_reports','flow_runs','crawl_runs','watchlist_command_logs','external_offers',
    'integration_runs','strategy_backtests','strategy_evaluations','opportunities',
    'verification_audits','product_events','source_health_history','notifications',
    'notification_deliveries'
  ]
  loop
    execute format('drop policy if exists authenticated_read on public.%I', t);
    execute format('create policy authenticated_read on public.%I for select to authenticated using (true)', t);
  end loop;
end $$;

insert into storage.buckets (id, name, public)
values
  ('price-evidence', 'price-evidence', false),
  ('product-images', 'product-images', true),
  ('report-exports', 'report-exports', false)
on conflict (id) do nothing;

drop policy if exists authenticated_read_price_evidence on storage.objects;
create policy authenticated_read_price_evidence
on storage.objects for select to authenticated
using (bucket_id in ('price-evidence','product-images','report-exports'));

drop policy if exists authenticated_write_price_evidence on storage.objects;
create policy authenticated_write_price_evidence
on storage.objects for insert to authenticated
with check (bucket_id in ('price-evidence','product-images','report-exports'));
