-- Manual purchase decisions only. No account, address, payment, or order data is stored.

create table if not exists public.purchase_confirmations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  price_record_id bigint not null references public.price_records(id) on delete restrict,
  product_name text not null,
  source_url text,
  checkout_price numeric(12,2) not null check (checkout_price > 0),
  currency text not null default 'CNY',
  status text not null default 'CONFIRMED' check (status in ('CONFIRMED','COMPLETED','CANCELLED')),
  note text,
  confirmed_by text not null,
  confirmed_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_purchase_confirmations_confirmed_at
on public.purchase_confirmations (confirmed_at desc, id desc);

alter table public.purchase_confirmations enable row level security;

revoke all on table public.purchase_confirmations from anon, authenticated;
grant select, insert, update, delete on table public.purchase_confirmations to service_role;
grant usage, select on sequence public.purchase_confirmations_id_seq to service_role;

drop policy if exists purchase_confirmations_service_role_all on public.purchase_confirmations;
create policy purchase_confirmations_service_role_all
on public.purchase_confirmations
for all
to service_role
using (true)
with check (true);
